##### Numpy

- pandas : https://pandas.pydata.org/
- Numpy : https://numpy.org/

- 수치해서, 수학적 처리를 위한 라이브러리(모듈) - Scipy, Pandas, Matploplib

##### Numbpy설치
!pip install numpy

In [1]:
# 현재 버전확인
!pip list

Package           Version
----------------- -------
asttokens         2.2.1
backcall          0.2.0
colorama          0.4.6
comm              0.1.3
contourpy         1.1.0
cycler            0.11.0
debugpy           1.6.7
decorator         5.1.1
et-xmlfile        1.1.0
executing         1.2.0
Faker             18.0.0
fonttools         4.40.0
ipykernel         6.23.2
ipython           8.14.0
jedi              0.18.2
Jinja2            3.1.2
jupyter_client    8.2.0
jupyter_core      5.3.1
kiwisolver        1.4.4
MarkupSafe        2.1.3
matplotlib        3.7.1
matplotlib-inline 0.1.6
nest-asyncio      1.5.6
numpy             1.25.0
openpyxl          3.1.2
packaging         23.1
pandas            2.0.2
parso             0.8.3
pickleshare       0.7.5
Pillow            9.5.0
pip               23.1.2
platformdirs      3.7.0
prompt-toolkit    3.0.38
psutil            5.9.5
pure-eval         0.2.2
Pygments          2.15.1
PyMySQL           1.0.3
pyparsing         3.1.0
python-dateutil   2.8.2
pyt

In [2]:
!pip install numpy

In [3]:
!pip install pandas


In [4]:
#import
import pandas as pd
import numpy as np

##### numpy를 쓰는 이유
- python 리스트를 만들면 사용처리(1,000,000건) - 260ms
- numpy배열을 만들고 처리하는데(1,000,000건) - 34.3ms(8배정도 빠름)

In [12]:
py_list = list(range(1_000_000)) # 100만건 리스트 만들기

In [11]:
np_arr = np.arange(1_000_000)

In [13]:
# 파이썬 리스트 사용
%timeit for _ in range(10): py_list2 = py_list * 2

161 ms ± 4.27 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [14]:
## 넘파이로 리스트 사용
%timeit for _ in range(10): np_arr2 = np_arr * 2

15.6 ms ± 309 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


##### 넘파이로 배열 생성, 연산등

- 파이썬 리스트는 + (리스트끼리), *(숫자만) 연산 밖에 없음
- 행렬(벡터)로 연산을 하고 싶으면 numpy배열로 형변환 후에 처리할 것

In [15]:
# 생성
np_arr1 = np.array([1, 3, 5])
np_arr1

array([1, 3, 5])

In [18]:
# 2차원 배열
np_arr2 = np.array([[1, 3, 5], [1,3,5]])
np_arr2

array([[1, 3, 5],
       [1, 3, 5]])

In [20]:
# 3차원 배열
np_arr3 = np.array([[[0, 2, 4], [8,10,12]], [[1, 3, 5], [7,9,12]]])
np_arr3

array([[[ 0,  2,  4],
        [ 8, 10, 12]],

       [[ 1,  3,  5],
        [ 7,  9, 12]]])

In [21]:
# 파이썬기본 리스트(배열)
list1=[1,3,5]
list1

[1, 3, 5]

In [22]:
# [1,3,5], [1,3,5] 는 튜플로 1차원 배열이 두개 만들어짐 #numpy에서는 허용안됨
# [[1,3,5], [1,3,5]] 2차원배열
list2 = [1,3,5], [1,3,5]
list2

([1, 3, 5], [1, 3, 5])

In [23]:
np_arr4 = np.zeros(4)
np_arr4

array([0., 0., 0., 0.])

In [24]:
np_arr5 = np.zeros([2,3])
np_arr5

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np_arr6 = np.empty((2, 3))
np_arr6

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
# 랜덤은 활용도 있음
np.random.randn(2,3)

array([[-0.77660558,  0.00525392,  0.981461  ],
       [ 0.21640935, -0.16177071,  0.96667827]])

In [33]:
np_arr7 = np.arange(10)

In [30]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [31]:
# 파이썬에서 리스트만든 다음에 numpy형태의 배열로 변경
np.array(list(range(10)))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np_arr7 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
np_arr7 * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [36]:
np_arr7/ 4

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25])

In [37]:
np_arr7 // 2

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4], dtype=int32)

In [38]:
# numpy 배열은 +더하기 연산
np_arr7 + np_arr7

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [42]:
# 파이썬 리스트 + concat(두 리스트를 합침)
list(range(10)) + list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [40]:
# 비교연산
(np_arr7 + np_arr7)<9

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [41]:
(np_arr7 + np_arr7) != 10

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True])

In [43]:
# 조회
np_arr7[1]

1

In [45]:
# 인덱스 크기를 벗어나면 indexerror 예외발생
np_arr7[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [48]:
np_arr7[np_arr7 < 5 ]

array([0, 1, 2, 3, 4])

In [49]:
list2 = list(range(10))
list2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [50]:
[x for x in range(10) if x < 5]

[0, 1, 2, 3, 4]

In [ ]:
np_arr7[3:9] # 뒤에 인덱스는 향상 -1

In [54]:
# 값 변경(치환)
np_arr7[np_arr7<5] = 100
np_arr7

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

##### 속성

- shape, dtype, T

In [55]:
np_arr1.shape

(3,)

In [56]:
np_arr2.shape

(2, 2, 3)

In [57]:
np_arr2.dtype

dtype('int32')

In [58]:
#Pivot
np_arr2.T

array([[[ 0,  1],
        [ 8,  7]],

       [[ 2,  3],
        [10,  9]],

       [[ 4,  5],
        [12, 12]]])

In [59]:
np_arr2.T.shape

(3, 2, 2)

In [60]:
##### 기타함수

In [61]:
np_arr8 = np.arange(10)
np_arr8

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
np_arr8.mean()

4.5

In [63]:
np_arr9 = np.random.randn(10)
np_arr9

array([ 0.22811205, -0.05273329, -0.58911622,  0.19153044, -1.47653624,
       -1.05589003,  0.32161919,  1.14625591,  2.16559017, -0.2374313 ])

In [64]:
#오름차순 정렬
np_arr9.sort()

In [65]:
np_arr9

array([-1.47653624, -1.05589003, -0.58911622, -0.2374313 , -0.05273329,
        0.19153044,  0.22811205,  0.32161919,  1.14625591,  2.16559017])

In [67]:
# 내림차순 정렬
-np.sort(-np_arr9)

array([ 2.16559017,  1.14625591,  0.32161919,  0.22811205,  0.19153044,
       -0.05273329, -0.2374313 , -0.58911622, -1.05589003, -1.47653624])

##### 테스트용 데이터프레임 예제

In [78]:
#####테스트용 테이터프레임 만들기
size = 10
df = pd.DataFrame({
    'class' : [['A', 'B', 'C', 'D', 'F'][np.random.randint(0, 5)] for i in range(0,size)],
    'year' : [np.random.randint(2010, 2024) for i in range(0,size)],
    'month' : [np.random.randint(1,13) for i in range(0, size)],
    'val1' : [np.random.randint(1,11) for i in range(0,size)],
    'val2' : [np.random.randint(100,1000) for i in range(0,size)],
    'val3' : [np.random.randint(10000,20000) for i in range(0,size)]

})
df

class  year  month  val1  val2   val3
0     D  2020      1     5   821  18630
1     A  2021     12     3   721  10534
2     C  2013      7     3   109  13271
3     F  2015      5    10   934  11762
4     D  2011     12     2   579  16070
5     F  2012      4     4   412  10294
6     C  2014     11     5   338  13734
7     A  2010      8     5   593  17280
8     D  2023      7     7   838  14650
9     D  2014      8     7   908  18259

In [79]:
df.dtypes

class    object
year      int64
month     int64
val1      int64
val2      int64
val3      int64
dtype: object

In [80]:
df.T


0      1      2      3      4      5      6      7      8      9
class      D      A      C      F      D      F      C      A      D      D
year    2020   2021   2013   2015   2011   2012   2014   2010   2023   2014
month      1     12      7      5     12      4     11      8      7      8
val1       5      3      3     10      2      4      5      5      7      7
val2     821    721    109    934    579    412    338    593    838    908
val3   18630  10534  13271  11762  16070  10294  13734  17280  14650  18259